/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AssignCategory: typeof import('./src/components/AssignCategory.vue')['default']
    Avatar: typeof import('primevue/avatar')['default']
    Button: typeof import('primevue/button')['default']
    Chart: typeof import('primevue/chart')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Divider: typeof import('primevue/divider')['default']
    Drawer: typeof import('primevue/drawer')['default']
    DynamicDialog: typeof import('primevue/dynamicdialog')['default']
    Expenses: typeof import('./src/components/Expenses.vue')['default']
    ExpensesDashboard: typeof import('./src/components/ExpensesDashboard.vue')['default']
    ExpensesTable: typeof import('./src/components/ExpensesTable.vue')['default']
    FileUpload: typeof import('primevue/fileupload')['default']
    FileUploadDialog: typeof import('./src/components/FileUploadDialog.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    IftaLabel: typeof import('primevue/iftalabel')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Menubar: typeof import('primevue/menubar')['default']
    Message: typeof import('primevue/message')['default']
    ProgressBar: typeof import('primevue/progressbar')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RadioButton: typeof import('primevue/radiobutton')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    Tag: typeof import('primevue/tag')['default']
    TheCategories: typeof import('./src/components/TheCategories.vue')['default']
    TheDrawer: typeof import('./src/components/TheDrawer.vue')['default']
    TheExpenses: typeof import('./src/components/TheExpenses.vue')['default']
    TheReports: typeof import('./src/components/TheReports.vue')['default']
    TheTempComponent: typeof import('./src/components/TheTempComponent.vue')['default']
    TheTimeline: typeof import('./src/components/TheTimeline.vue')['default']
    Toast: typeof import('primevue/toast')['default']
    Tree: typeof import('primevue/tree')['default']
  }
  export interface GlobalDirectives {
    Ripple: typeof import('primevue/ripple')['default']
    StyleClass: typeof import('primevue/styleclass')['default']
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}

// For TSX support
declare global {
  const AssignCategory: typeof import('./src/components/AssignCategory.vue')['default']
  const Avatar: typeof import('primevue/avatar')['default']
  const Button: typeof import('primevue/button')['default']
  const Chart: typeof import('primevue/chart')['default']
  const Checkbox: typeof import('primevue/checkbox')['default']
  const Column: typeof import('primevue/column')['default']
  const DataTable: typeof import('primevue/datatable')['default']
  const Dialog: typeof import('primevue/dialog')['default']
  const Divider: typeof import('primevue/divider')['default']
  const Drawer: typeof import('primevue/drawer')['default']
  const DynamicDialog: typeof import('primevue/dynamicdialog')['default']
  const Expenses: typeof import('./src/components/Expenses.vue')['default']
  const ExpensesDashboard: typeof import('./src/components/ExpensesDashboard.vue')['default']
  const ExpensesTable: typeof import('./src/components/ExpensesTable.vue')['default']
  const FileUpload: typeof import('primevue/fileupload')['default']
  const FileUploadDialog: typeof import('./src/components/FileUploadDialog.vue')['default']
  const HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
  const IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
  const IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
  const IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
  const IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
  const IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
  const IftaLabel: typeof import('primevue/iftalabel')['default']
  const InputText: typeof import('primevue/inputtext')['default']
  const Menubar: typeof import('primevue/menubar')['default']
  const Message: typeof import('primevue/message')['default']
  const ProgressBar: typeof import('primevue/progressbar')['default']
  const ProgressSpinner: typeof import('primevue/progressspinner')['default']
  const RadioButton: typeof import('primevue/radiobutton')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const Select: typeof import('primevue/select')['default']
  const Tag: typeof import('primevue/tag')['default']
  const TheCategories: typeof import('./src/components/TheCategories.vue')['default']
  const TheDrawer: typeof import('./src/components/TheDrawer.vue')['default']
  const TheExpenses: typeof import('./src/components/TheExpenses.vue')['default']
  const TheReports: typeof import('./src/components/TheReports.vue')['default']
  const TheTempComponent: typeof import('./src/components/TheTempComponent.vue')['default']
  const TheTimeline: typeof import('./src/components/TheTimeline.vue')['default']
  const Toast: typeof import('primevue/toast')['default']
  const Tree: typeof import('primevue/tree')['default']
}